# Generated by Django 2.2 on 2021-10-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('V', 'vegetables'), ('F', 'Fruits'), ('C', 'Cereals')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('I', 'danger'), ('KG', 'primary'), ('B', 'success')], max_length=1, null=True),
        ),
    ]
