# Generated by Django 2.2 on 2021-10-13 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20211013_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_image',
            new_name='image',
        ),
    ]
